

import java.awt.CardLayout;
import javax.swing.tree.TreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HAP
 */
public class MathJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MathJFrame() {
        initComponents();
        
        //expand all the nodes of the math tree
        treeMath.expandRow(0);
        treeMath.expandRow(1);
        treeMath.expandRow(3); 
        treeMath.expandRow(5);
      
        
        //set the root node is selected, so the welcome panel is showed
        treeMath.setSelectionRow(0);
      
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGro1 = new javax.swing.ButtonGroup();
        btnGro2 = new javax.swing.ButtonGroup();
        btnGro3 = new javax.swing.ButtonGroup();
        btnGro4 = new javax.swing.ButtonGroup();
        btnGro5 = new javax.swing.ButtonGroup();
        btnGro6 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeMath = new javax.swing.JTree();
        panContent = new javax.swing.JPanel();
        panFactorial = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaFactorial = new javax.swing.JTextArea();
        panFactorialExe = new javax.swing.JPanel();
        lblFactorialExeTitle = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        btn4 = new javax.swing.JButton();
        txtA2 = new javax.swing.JTextArea();
        txtA1 = new javax.swing.JTextArea();
        txtA3 = new javax.swing.JTextArea();
        txtA4 = new javax.swing.JTextArea();
        panPrime = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaPrime = new javax.swing.JTextArea();
        panPrimeTest = new javax.swing.JPanel();
        lblPrimeTest1 = new javax.swing.JLabel();
        lblPrimeTest = new javax.swing.JLabel();
        rBtnYes1 = new javax.swing.JRadioButton();
        rBtnNo1 = new javax.swing.JRadioButton();
        lblPrimeTest2 = new javax.swing.JLabel();
        rBtnYes2 = new javax.swing.JRadioButton();
        rBtnNo2 = new javax.swing.JRadioButton();
        lblPrimeTest3 = new javax.swing.JLabel();
        rBtnYes3 = new javax.swing.JRadioButton();
        rBtnNo3 = new javax.swing.JRadioButton();
        lblPrimeTest4 = new javax.swing.JLabel();
        rBtnYes4 = new javax.swing.JRadioButton();
        rBtnNo4 = new javax.swing.JRadioButton();
        lblPrimeTest5 = new javax.swing.JLabel();
        rBtnYes5 = new javax.swing.JRadioButton();
        rBtnNo5 = new javax.swing.JRadioButton();
        lblPrimeTest6 = new javax.swing.JLabel();
        rBtnYes6 = new javax.swing.JRadioButton();
        rBtnNo6 = new javax.swing.JRadioButton();
        btnReTestPrime = new javax.swing.JButton();
        btnCheckPrime = new javax.swing.JButton();
        lblCheck1 = new javax.swing.JLabel();
        lblCheck2 = new javax.swing.JLabel();
        lblCheck3 = new javax.swing.JLabel();
        lblCheck4 = new javax.swing.JLabel();
        lblCheck5 = new javax.swing.JLabel();
        lblCheck6 = new javax.swing.JLabel();
        panBinAndDec = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaBinAndDec = new javax.swing.JTextArea();
        panBinToDec = new javax.swing.JPanel();
        lblPanBinToDec = new javax.swing.JLabel();
        panDecToBin = new javax.swing.JPanel();
        lblPanDecToBin1 = new javax.swing.JLabel();
        lblPanDecToBin2 = new javax.swing.JLabel();
        lblPanDecToBin3 = new javax.swing.JLabel();
        txtAPanDecToBin = new javax.swing.JTextArea();
        lblPanDecToBin4 = new javax.swing.JLabel();
        panBinAndDecConverter = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDec = new javax.swing.JLabel();
        lblBin = new javax.swing.JLabel();
        txtDecToBin = new javax.swing.JTextField();
        txtBinToDec = new javax.swing.JTextField();
        btnDecToBin = new javax.swing.JButton();
        btnBinToDec = new javax.swing.JButton();
        lblDecToBin = new javax.swing.JLabel();
        lblBinToDec = new javax.swing.JLabel();
        panWelcome = new javax.swing.JPanel();
        txtAWelcome = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome to the math classroom");
        setLocation(new java.awt.Point(160, 60));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 600));

        jSplitPane1.setDividerLocation(220);

        treeMath.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Math Tutorial");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Factorial");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("exercise");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Prime");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("test");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Binary and Decimal");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bin to dec");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("dec to bin");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("converter");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeMath.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeMath.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeMathValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeMath);

        jSplitPane1.setLeftComponent(jScrollPane1);

        panContent.setLayout(new java.awt.CardLayout());

        panFactorial.setLayout(new java.awt.BorderLayout());

        txtaFactorial.setColumns(20);
        txtaFactorial.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtaFactorial.setForeground(new java.awt.Color(0, 51, 204));
        txtaFactorial.setRows(5);
        txtaFactorial.setText("Determining Factorials\n\n A factorial is the product of multiplying every number together, \n from 1 to a given number. It’s denoted by writing n!\n\n Does that make sense? Let’s look at an example.\n\n The factorial of 6 would be:\n\n 6! = 6 x 5 x 4 x 3 x 2 x 1\n 6! = 720\n\n Cool, eh?\n");
        jScrollPane2.setViewportView(txtaFactorial);

        panFactorial.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panContent.add(panFactorial, "panFactorial");

        panFactorialExe.setBackground(new java.awt.Color(204, 204, 255));
        panFactorialExe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFactorialExeTitle.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        lblFactorialExeTitle.setText("Questions:");
        panFactorialExe.add(lblFactorialExeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 151, 40));

        lbl1.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lbl1.setText("1. What is the factorial of 5 ?");
        panFactorialExe.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 296, -1));

        btn1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        btn1.setText("Answer");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        panFactorialExe.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 131, -1, -1));

        lbl2.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lbl2.setText("2. What is the factorial of 8?");
        panFactorialExe.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, 296, -1));

        btn2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        btn2.setText("Answer");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        panFactorialExe.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 411, -1, -1));

        lbl3.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lbl3.setText("3. What is the factorial of 10 ?");
        panFactorialExe.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 92, 296, -1));

        btn3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        btn3.setText("Answer");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panFactorialExe.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 131, -1, -1));

        lbl4.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lbl4.setText("4. What is the factorial of 3 ?");
        panFactorialExe.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 358, 296, -1));

        btn4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        btn4.setText("Answer");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panFactorialExe.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 411, -1, -1));

        txtA2.setEditable(false);
        txtA2.setColumns(20);
        txtA2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtA2.setRows(2);
        txtA2.setText("8! = 8 x 7 x 6 x 5 x 4 x 3 x 2 x 1\n8! = 40320");
        txtA2.setBorder(null);
        panFactorialExe.add(txtA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 467, 366, 70));

        txtA1.setEditable(false);
        txtA1.setColumns(20);
        txtA1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtA1.setRows(2);
        txtA1.setText("5! = 5 x 4 x 3 x 2 x 1\n5! = 120");
        txtA1.setBorder(null);
        txtA1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        panFactorialExe.add(txtA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 185, 326, 70));

        txtA3.setEditable(false);
        txtA3.setColumns(20);
        txtA3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtA3.setRows(2);
        txtA3.setText("10! = 10 x 9 x 8 x 7 x 6 x 5 x 4 x 3 x 2 x 1\n10! = 3628800");
        txtA3.setBorder(null);
        panFactorialExe.add(txtA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 371, 83));

        txtA4.setEditable(false);
        txtA4.setColumns(20);
        txtA4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtA4.setRows(2);
        txtA4.setText("3! = 3 x 2 x 1\n3! = 6");
        txtA4.setBorder(null);
        panFactorialExe.add(txtA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 467, 311, 70));

        panContent.add(panFactorialExe, "panFactorialExe");

        panPrime.setLayout(new java.awt.BorderLayout());

        txtaPrime.setColumns(20);
        txtaPrime.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtaPrime.setForeground(new java.awt.Color(0, 51, 204));
        txtaPrime.setRows(5);
        txtaPrime.setText("Prime Numbers\n\nPrime numbers are numbers that are only divisible by themselves and 1.\n\nA number is divisible by another number if you can divide it \nwithout being left with any remainders.\n\n12 is divisible by 6 because 12 % 6 = 0.\nBut 23 is not divisible by 6 because 23 % 6 = 5.\n\nImagine you had to determine whether or not 7 was a prime number.\nYour brain might do something like this:\nIs 7 divisible by 2? No.\nIs 7 divisible by 3? No.\nIs 7 divisible by 4? No.\nIs 7 divisible by 5? No.\nIs 7 divisible by 6? No.\n\n\nSo, 7 is a prime number. Hooray!!");
        jScrollPane3.setViewportView(txtaPrime);

        panPrime.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panContent.add(panPrime, "panPrime");

        panPrimeTest.setBackground(new java.awt.Color(204, 204, 255));
        panPrimeTest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrimeTest1.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest1.setText("1. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 296, -1));

        lblPrimeTest.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        lblPrimeTest.setText("Prime Test:");
        panPrimeTest.add(lblPrimeTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 151, 40));

        btnGro1.add(rBtnYes1);
        rBtnYes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes1.setSelected(true);
        rBtnYes1.setText("Yes");
        rBtnYes1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes1ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        btnGro1.add(rBtnNo1);
        rBtnNo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo1.setText("No");
        panPrimeTest.add(rBtnNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        lblPrimeTest2.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest2.setText("2. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 296, -1));

        btnGro2.add(rBtnYes2);
        rBtnYes2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes2.setSelected(true);
        rBtnYes2.setText("Yes");
        rBtnYes2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes2ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        btnGro2.add(rBtnNo2);
        rBtnNo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo2.setText("No");
        panPrimeTest.add(rBtnNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        lblPrimeTest3.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest3.setText("3. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 296, -1));

        btnGro3.add(rBtnYes3);
        rBtnYes3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes3.setSelected(true);
        rBtnYes3.setText("Yes");
        rBtnYes3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes3ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        btnGro3.add(rBtnNo3);
        rBtnNo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo3.setText("No");
        panPrimeTest.add(rBtnNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        lblPrimeTest4.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest4.setText("4. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 296, -1));

        btnGro4.add(rBtnYes4);
        rBtnYes4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes4.setSelected(true);
        rBtnYes4.setText("Yes");
        rBtnYes4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes4ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        btnGro4.add(rBtnNo4);
        rBtnNo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo4.setText("No");
        panPrimeTest.add(rBtnNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        lblPrimeTest5.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest5.setText("5. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 296, -1));

        btnGro5.add(rBtnYes5);
        rBtnYes5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes5.setSelected(true);
        rBtnYes5.setText("Yes");
        rBtnYes5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes5ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        btnGro5.add(rBtnNo5);
        rBtnNo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo5.setText("No");
        panPrimeTest.add(rBtnNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        lblPrimeTest6.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        lblPrimeTest6.setText("6. Is  5  a prime number ?");
        panPrimeTest.add(lblPrimeTest6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 296, -1));

        btnGro6.add(rBtnYes6);
        rBtnYes6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnYes6.setSelected(true);
        rBtnYes6.setText("Yes");
        rBtnYes6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnYes6ItemStateChanged(evt);
            }
        });
        panPrimeTest.add(rBtnYes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        btnGro6.add(rBtnNo6);
        rBtnNo6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnNo6.setText("No");
        panPrimeTest.add(rBtnNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        btnReTestPrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReTestPrime.setText("ReTest");
        btnReTestPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReTestPrimeActionPerformed(evt);
            }
        });
        panPrimeTest.add(btnReTestPrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 539, 110, -1));

        btnCheckPrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCheckPrime.setText("Check");
        btnCheckPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPrimeActionPerformed(evt);
            }
        });
        panPrimeTest.add(btnCheckPrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 539, 110, -1));

        lblCheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblCheck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblCheck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblCheck4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        lblCheck5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        lblCheck6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.jpg"))); // NOI18N
        panPrimeTest.add(lblCheck6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        panContent.add(panPrimeTest, "panPrimeTest");

        panBinAndDec.setLayout(new java.awt.BorderLayout());

        txtaBinAndDec.setColumns(20);
        txtaBinAndDec.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtaBinAndDec.setForeground(new java.awt.Color(0, 51, 204));
        txtaBinAndDec.setRows(5);
        txtaBinAndDec.setText("Binary\n\n Binary is a number system that uses 2 as it’s base. \n The binary number system uses only two digits: 0 and 1. \n Using 0s and 1s, the computer can represent any number imaginable.\n \n for example: 11001, 101011011010\n\n\nDecimal\n\n Decimal is a number system that uses10 as it’s base.\n The decimal number system uses 10 different digits \n (0, 1, 2, 3, 4, 5, 6, 7, 8 and 9).\n\n for example : 65, 83");
        jScrollPane5.setViewportView(txtaBinAndDec);

        panBinAndDec.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        panContent.add(panBinAndDec, "panBinAndDec");

        panBinToDec.setBackground(new java.awt.Color(255, 255, 255));
        panBinToDec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPanBinToDec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bintodec.jpg"))); // NOI18N
        lblPanBinToDec.setText("jLabel4");
        panBinToDec.add(lblPanBinToDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 840, 410));

        panContent.add(panBinToDec, "panBinToDec");

        panDecToBin.setBackground(new java.awt.Color(255, 255, 255));
        panDecToBin.setForeground(new java.awt.Color(255, 255, 255));

        lblPanDecToBin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decToBin1.jpg"))); // NOI18N
        lblPanDecToBin1.setText("jLabel5");

        lblPanDecToBin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decToBin2.jpg"))); // NOI18N
        lblPanDecToBin2.setText("jLabel6");

        lblPanDecToBin3.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        lblPanDecToBin3.setForeground(new java.awt.Color(0, 51, 153));
        lblPanDecToBin3.setText("Convert deciaml to binary:");

        txtAPanDecToBin.setEditable(false);
        txtAPanDecToBin.setColumns(20);
        txtAPanDecToBin.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtAPanDecToBin.setForeground(new java.awt.Color(5, 1, 153));
        txtAPanDecToBin.setRows(5);
        txtAPanDecToBin.setText("\nDivide the positive decimal number by two, then divide the quotient by two,\nand so on until the quotient is zero or one, then mark the remainder \nof each step, finaly arrange remainder in reverse order.");

        lblPanDecToBin4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        lblPanDecToBin4.setForeground(new java.awt.Color(5, 1, 153));
        lblPanDecToBin4.setText("remainder");

        javax.swing.GroupLayout panDecToBinLayout = new javax.swing.GroupLayout(panDecToBin);
        panDecToBin.setLayout(panDecToBinLayout);
        panDecToBinLayout.setHorizontalGroup(
            panDecToBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDecToBinLayout.createSequentialGroup()
                .addGroup(panDecToBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDecToBinLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblPanDecToBin2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPanDecToBin1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDecToBinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPanDecToBin3))
                    .addComponent(txtAPanDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panDecToBinLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblPanDecToBin4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        panDecToBinLayout.setVerticalGroup(
            panDecToBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDecToBinLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPanDecToBin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAPanDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPanDecToBin4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDecToBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDecToBinLayout.createSequentialGroup()
                        .addComponent(lblPanDecToBin2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDecToBinLayout.createSequentialGroup()
                        .addComponent(lblPanDecToBin1)
                        .addGap(139, 139, 139))))
        );

        panContent.add(panDecToBin, "panDecToBin");

        panBinAndDecConverter.setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle.setText("Binary and Decimal Converter");

        lblDec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDec.setText("Enter a decimal number");

        lblBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBin.setText("Enter a binary number");

        txtDecToBin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtBinToDec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDecToBin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDecToBin.setText("Dec. To Bin.");
        btnDecToBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBinActionPerformed(evt);
            }
        });

        btnBinToDec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBinToDec.setText("Bin. To Dec.");
        btnBinToDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinToDecActionPerformed(evt);
            }
        });

        lblDecToBin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDecToBin.setText("Decimal and Binary");

        lblBinToDec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBinToDec.setText("Decimal and Binary");

        javax.swing.GroupLayout panBinAndDecConverterLayout = new javax.swing.GroupLayout(panBinAndDecConverter);
        panBinAndDecConverter.setLayout(panBinAndDecConverterLayout);
        panBinAndDecConverterLayout.setHorizontalGroup(
            panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                                .addComponent(lblBin, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBinToDec, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                                .addComponent(lblDec, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBinAndDecConverterLayout.createSequentialGroup()
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnBinToDec)
                        .addGap(93, 93, 93)
                        .addComponent(lblBinToDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnDecToBin)
                        .addGap(76, 76, 76)
                        .addComponent(lblDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panBinAndDecConverterLayout.setVerticalGroup(
            panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBinAndDecConverterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDecToBin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBinToDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBinAndDecConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBinToDec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBinToDec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );

        panContent.add(panBinAndDecConverter, "panBinAndDecConverter");

        panWelcome.setBackground(new java.awt.Color(204, 204, 255));

        txtAWelcome.setBackground(new java.awt.Color(204, 204, 255));
        txtAWelcome.setColumns(20);
        txtAWelcome.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 48)); // NOI18N
        txtAWelcome.setForeground(new java.awt.Color(255, 0, 102));
        txtAWelcome.setRows(5);
        txtAWelcome.setText("         Welcome to \n\nthe Math Classroom");
        txtAWelcome.setBorder(null);

        javax.swing.GroupLayout panWelcomeLayout = new javax.swing.GroupLayout(panWelcome);
        panWelcome.setLayout(panWelcomeLayout);
        panWelcomeLayout.setHorizontalGroup(
            panWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWelcomeLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(txtAWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        panWelcomeLayout.setVerticalGroup(
            panWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWelcomeLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(txtAWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        panContent.add(panWelcome, "panWelcome");

        jSplitPane1.setRightComponent(panContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void treeMathValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeMathValueChanged
        // TODO add your handling code here:
       Object object = treeMath.getLastSelectedPathComponent();
        if (object == null){
          return;
        }
        CardLayout card = (CardLayout)panContent.getLayout();
        TreeNode node = (TreeNode) object;
        String value = node.toString();
       
        //different node matches diffrent panel
        if(value.equals("Math Tutorial"))
        {
           
            card.show(panContent, "panWelcome");
             return;   
        }
        else if(value.equals("Factorial"))
        {
            card.show(panContent, "panFactorial");
             return;   
        }
        else if(value.equals("Prime"))
        {
            card.show(panContent, "panPrime");
             return;   
        }
        else if(value.equals("Binary and Decimal"))
        {
            card.show(panContent, "panBinAndDec");
             return;   
        }
        
        TreeNode parent = node.getParent();
        String parentValue = parent.toString();
        
       
       if( parentValue.equals("Prime"))
       {
           if(value.equals("test"))
           {
              initPanPrimeTest();
               card.show(panContent,"panPrimeTest");
           }
       }
       else if( parentValue.equals("Factorial"))
       {
           
           if(value.equals("exercise"))
           { 
               //when initial the factorial exercise panel, the answers are not visible.
               txtA1.setVisible(false);
               txtA2.setVisible(false);
               txtA3.setVisible(false);
               txtA4.setVisible(false);
               card.show(panContent,"panFactorialExe");
           }
       }
       else if( parentValue.equals("Binary and Decimal"))
       {
           
           if(value.equals("bin to dec"))
           { 
             
             card.show(panContent,"panBinToDec");
           }
           else if(value.equals("dec to bin"))
           { 
             
             card.show(panContent,"panDecToBin");
           }
           else if(value.equals("converter"))
           { 
             
             card.show(panContent,"panBinAndDecConverter");
           }
           
           
       }
       
      

    }//GEN-LAST:event_treeMathValueChanged

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // chang the visible value of the answer
        txtA1.setVisible(!txtA1.isVisible());
       
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // chang the visible value of the answer
         txtA2.setVisible(!txtA2.isVisible());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         txtA3.setVisible(!txtA3.isVisible());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
         txtA4.setVisible(!txtA4.isVisible());
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnDecToBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToBinActionPerformed
        int origInt = 0;
        String result;
        
        try
        {
            origInt = Integer.parseInt(txtDecToBin.getText());
            result = decimalToBinary(origInt);
            lblDecToBin.setText(result);
        }
        catch(Exception e)
        {
            lblDecToBin.setText("This is not a correct number !");
            txtDecToBin.setText("");
            return;
        }
    }//GEN-LAST:event_btnDecToBinActionPerformed

    private void btnBinToDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinToDecActionPerformed
        String origStr ;       //a bianry  number inputed by user
        String revStr = "";    
        int binToDec = 0;       //the result of converting bianry to decimal
         
        origStr = txtBinToDec.getText();
        
         // reverse the binary number
        revStr = getRevStr(origStr);
        
        try
        {
            
            binToDec = binaryToDecimal(revStr);
            if(binToDec == -1)
            {
                lblBinToDec.setText("This is not a binary number !");
                txtBinToDec.setText("");
            }
            else
            {
                  lblBinToDec.setText(String.valueOf(binToDec));
            
            }
        }
        catch(Exception e)
        {
            lblBinToDec.setText("This is not a binary number !");
             txtBinToDec.setText("");
            return;
        }
    }//GEN-LAST:event_btnBinToDecActionPerformed

    private void btnReTestPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReTestPrimeActionPerformed
       
            initPanPrimeTest();
            isChecked = false;
      
    }//GEN-LAST:event_btnReTestPrimeActionPerformed

    private void btnCheckPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPrimeActionPerformed
      
        // if the answer selected by user is correct , show the smiling face label
        if((flags[0] == true && rBtnYes1.isSelected()== true) || (flags[0] == false && rBtnNo1.isSelected()== true))
        {
           lblCheck1.setVisible(true);
        }
        else
        {
            lblCheck1.setVisible(false);
        }
        
       if((flags[1] == true && rBtnYes2.isSelected()== true) || (flags[1] == false && rBtnNo2.isSelected()== true))
        {
           lblCheck2.setVisible(true);
        }
        else
        {
            lblCheck2.setVisible(false);
        }
       
        if((flags[2] == true && rBtnYes3.isSelected()== true) || (flags[2] == false && rBtnNo3.isSelected()== true))
        {
           lblCheck3.setVisible(true);
        }
        else
        {
            lblCheck3.setVisible(false);
        }
        
       if((flags[3] == true && rBtnYes4.isSelected()== true) || (flags[3] == false && rBtnNo4.isSelected()== true))
        {
           lblCheck4.setVisible(true);
        }
        else
        {
            lblCheck4.setVisible(false);
        }
       
       if((flags[4] == true && rBtnYes5.isSelected()== true) || (flags[4] == false && rBtnNo5.isSelected()== true))
        {
           lblCheck5.setVisible(true);
        }
        else
        {
            lblCheck5.setVisible(false);
        }
       
      if((flags[5] == true && rBtnYes6.isSelected()== true) || (flags[5] == false && rBtnNo6.isSelected()== true))
        {
           lblCheck6.setVisible(true);
        }
        else
        {
            lblCheck6.setVisible(false);
        }
      
       isChecked = true;
      
    }//GEN-LAST:event_btnCheckPrimeActionPerformed

    private void changeLblCheckState()
    {
         if(isChecked == true) 
        {
             lblCheck1.setVisible(false);
             lblCheck2.setVisible(false);
             lblCheck3.setVisible(false);
             lblCheck4.setVisible(false);
             lblCheck5.setVisible(false);
             lblCheck6.setVisible(false);
        }
    }
    private void rBtnYes1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes1ItemStateChanged
       changeLblCheckState();
    }//GEN-LAST:event_rBtnYes1ItemStateChanged

    private void rBtnYes2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes2ItemStateChanged
       changeLblCheckState();
    }//GEN-LAST:event_rBtnYes2ItemStateChanged

    private void rBtnYes3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes3ItemStateChanged
       changeLblCheckState();
    }//GEN-LAST:event_rBtnYes3ItemStateChanged

    private void rBtnYes4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes4ItemStateChanged
       changeLblCheckState();
    }//GEN-LAST:event_rBtnYes4ItemStateChanged

    private void rBtnYes5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes5ItemStateChanged
        changeLblCheckState();
    }//GEN-LAST:event_rBtnYes5ItemStateChanged

    private void rBtnYes6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnYes6ItemStateChanged
       changeLblCheckState();
    }//GEN-LAST:event_rBtnYes6ItemStateChanged

    /**
     *  convert a decimal number to a binary number
     * @param num
     * @return string
     */
    private String decimalToBinary(int num) {
        String result = "";
        
        while(num > 0 ) 
        {
            
           
           //get the remainder
            result = num % 2  + result;
            
            // Divide the positive decimal number by two( then divide the quotient by two)
            num = num /2;
        }
        
        return result;
    }
    
    /** 
     * convert a bianry number to a decimal number
     * @param revStr
     * @return int
     */
    private int binaryToDecimal(String revStr){
        String tempStr ;
        int tempInt;
        int result = 0;
        
        for(int i =0; i < revStr.length(); i++)
        {
            tempStr = String.valueOf(revStr.charAt(i));
            tempInt = Integer.parseInt(tempStr);
            
            //if  the integer number  is not  1 or 0, the number inputed by user is not a bianry number 
            //so return -1;
            if(tempInt != 1 && tempInt != 0)
            {
                return -1;
            }
            
            //if the integer number is 0, skip this number
            if(tempInt == 0)
            {
                continue;
            }
            
            //if the integer number is 1 (tempInt = 1), calculate the power
            result = result + (int)(tempInt * Math.pow(2.0, (double)i));
        }
        
        return result;
    }
    
    /**
     * reverse string
     * @param origStr
     * @return 
     */
    private String getRevStr(String origStr) {
        String revStr = "";
        for(int i = origStr.length() - 1; i>= 0; i--)
        {
            revStr = revStr + origStr.charAt(i);
                
        }
        
        return revStr;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathJFrame().setVisible(true);
             
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnBinToDec;
    private javax.swing.JButton btnCheckPrime;
    private javax.swing.JButton btnDecToBin;
    private javax.swing.ButtonGroup btnGro1;
    private javax.swing.ButtonGroup btnGro2;
    private javax.swing.ButtonGroup btnGro3;
    private javax.swing.ButtonGroup btnGro4;
    private javax.swing.ButtonGroup btnGro5;
    private javax.swing.ButtonGroup btnGro6;
    private javax.swing.JButton btnReTestPrime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblBin;
    private javax.swing.JLabel lblBinToDec;
    private javax.swing.JLabel lblCheck1;
    private javax.swing.JLabel lblCheck2;
    private javax.swing.JLabel lblCheck3;
    private javax.swing.JLabel lblCheck4;
    private javax.swing.JLabel lblCheck5;
    private javax.swing.JLabel lblCheck6;
    private javax.swing.JLabel lblDec;
    private javax.swing.JLabel lblDecToBin;
    private javax.swing.JLabel lblFactorialExeTitle;
    private javax.swing.JLabel lblPanBinToDec;
    private javax.swing.JLabel lblPanDecToBin1;
    private javax.swing.JLabel lblPanDecToBin2;
    private javax.swing.JLabel lblPanDecToBin3;
    private javax.swing.JLabel lblPanDecToBin4;
    private javax.swing.JLabel lblPrimeTest;
    private javax.swing.JLabel lblPrimeTest1;
    private javax.swing.JLabel lblPrimeTest2;
    private javax.swing.JLabel lblPrimeTest3;
    private javax.swing.JLabel lblPrimeTest4;
    private javax.swing.JLabel lblPrimeTest5;
    private javax.swing.JLabel lblPrimeTest6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panBinAndDec;
    private javax.swing.JPanel panBinAndDecConverter;
    private javax.swing.JPanel panBinToDec;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panDecToBin;
    private javax.swing.JPanel panFactorial;
    private javax.swing.JPanel panFactorialExe;
    private javax.swing.JPanel panPrime;
    private javax.swing.JPanel panPrimeTest;
    private javax.swing.JPanel panWelcome;
    private javax.swing.JRadioButton rBtnNo1;
    private javax.swing.JRadioButton rBtnNo2;
    private javax.swing.JRadioButton rBtnNo3;
    private javax.swing.JRadioButton rBtnNo4;
    private javax.swing.JRadioButton rBtnNo5;
    private javax.swing.JRadioButton rBtnNo6;
    private javax.swing.JRadioButton rBtnYes1;
    private javax.swing.JRadioButton rBtnYes2;
    private javax.swing.JRadioButton rBtnYes3;
    private javax.swing.JRadioButton rBtnYes4;
    private javax.swing.JRadioButton rBtnYes5;
    private javax.swing.JRadioButton rBtnYes6;
    private javax.swing.JTree treeMath;
    private javax.swing.JTextArea txtA1;
    private javax.swing.JTextArea txtA2;
    private javax.swing.JTextArea txtA3;
    private javax.swing.JTextArea txtA4;
    private javax.swing.JTextArea txtAPanDecToBin;
    private javax.swing.JTextArea txtAWelcome;
    private javax.swing.JTextField txtBinToDec;
    private javax.swing.JTextField txtDecToBin;
    private javax.swing.JTextArea txtaBinAndDec;
    private javax.swing.JTextArea txtaFactorial;
    private javax.swing.JTextArea txtaPrime;
    // End of variables declaration//GEN-END:variables
   
    boolean [] flags = new boolean[6];
    boolean isChecked = false;
    
    private void initPanPrimeTest() {
         
        int [] numbers = new int[6];    
        for(int i = 0; i <6; i++)
        {
            //get a random number from 1 to 100
            numbers[i] =(int) Math.round(Math.random()* 100 +1);
            
            //determine whether the number is a prime or not
            flags[i] = determinePrime(numbers[i]);
            
        }
        
        lblPrimeTest1.setText("1. Is " + numbers[0] + " a prime number ?");
        lblPrimeTest2.setText("2. Is " + numbers[1] + " a prime number ?");
        lblPrimeTest3.setText("3. Is " + numbers[2] + " a prime number ?");
        lblPrimeTest4.setText("4. Is " + numbers[3] + " a prime number ?");
        lblPrimeTest5.setText("5. Is " + numbers[4] + " a prime number ?");
        lblPrimeTest6.setText("6. Is " + numbers[5] + " a prime number ?");
             
        rBtnYes1.setSelected(true);
        rBtnYes2.setSelected(true);
        rBtnYes3.setSelected(true);
        rBtnYes4.setSelected(true);
        rBtnYes5.setSelected(true);
        rBtnYes6.setSelected(true);
         
        lblCheck1.setVisible(false);
        lblCheck2.setVisible(false);
        lblCheck3.setVisible(false);
        lblCheck4.setVisible(false);
        lblCheck5.setVisible(false);
        lblCheck6.setVisible(false);
    }
    /**
     * determine whether a number is a prime or not
     * @param num
     * @return boolean
     */
    private boolean determinePrime(int num) {
        int temp;
        boolean isPrime = true;
        
        if(num <= 1)
        {
            isPrime = false;
        }
        else
        {
            for(int i = 2;i<=num/2; i++)
            {
                //divide the number by i, get the remainder 
                temp = num % i;
                
                //if remainder is 0, the number is not prime
                if(temp == 0)
                {
                    isPrime = false;
                    break;
                }
            }
        }
        
        return isPrime;
    }
}
